### ISSUE TITLE
Content not visible when wrapping paper-checkbox

### ISSUE THREAD

**Issue by stevenjb** [Polymer/paper-checkbox#26] opened 2015-08-13 22:47 UTC
After updating to version 1.0.6, our paper-checkbox wrapper broke. The <content> is no longer getting displayed. Our wrapper looks something like:

```
<dom-module id="custom-checkbox">
  <template>
    <paper-checkbox id="checkbox" checked="{{checked}}" disabled="[[disabled]]">
      <content></content>
    </paper-checkbox>
  </template>
  <script src="custom_checkbox.js"></script>
</dom-module>
```

This works:
<paper-checkbox>Paper Checkbox</paper-checkbox>

This doesn't show the label:
<my-checkbox>My Checkbox</my-checkbox>

**Comment by notwaldorf** [comment] 2015-08-13 23:08
This is broken because of the fix that I made to `this.$.checkboxLabel.hidden` -- pre 1.0.6, that code was actually never getting called, so the label was never hidden (since the content isn't guaranteed to be ready when the `paper-checkbox` fires its `ready()`

**Comment by notwaldorf** [comment] 2015-08-13 23:14
Closing this since it's in the wrong repo, and it's a duplicate of https://github.com/PolymerElements/paper-checkbox/issues/49

**Closed as completed by notwaldorf** 2015-08-13 23:14 UTC
