### ISSUE TITLE
mouse cursor over label does not display as pointer even though its clickable

### ISSUE THREAD

**Issue by sigmundch** [Polymer/paper-checkbox#13] opened 2014-09-04 00:01 UTC
Originally reported by @HannesRammer in https://github.com/dart-lang/paper-elements/issues/45

> mouse cursor over paper-checkbox label does not display as pointer even though its clickable.

**Comment by ssorallen** [comment] 2015-01-12 20:54
`cursor: default;` is the default for most user agents for `<label>`: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_label

I don't think Polymer should stray from the default.

**Comment by ssorallen** [comment] 2015-02-06 01:26
Material Design doesn't prescribe cursors for elements on desktop, and so it seems reasonable to defer to the user agent for defaults. Since `<label>` uses `cursor: default;` I'm going to close this as expected behavior.

**Closed by ssorallen** 2015-02-06 01:26 UTC
